function Radiomics = computeGLRLM(glrlm)
nMatrices = size(glrlm, 3);
nLength = size(glrlm, 2);
nLevels = size(glrlm, 1);
Radiomics.GLRLM_ShortRunEmphasis = 0;
Radiomics.GLRLM_LongRunEmphasis = 0;
Radiomics.GLRLM_GrayLevelNonUniformity = 0;
Radiomics.GLRLM_RunLengthNonUniformity = 0;
Radiomics.GLRLM_RunPercentage = 0;
Radiomics.GLRLM_LowGrayLevelRunEmphasis = 0;
Radiomics.GLRLM_HighGrayLevelRunEmphasis = 0;
Radiomics.GLRLM_ShortRunLowGrayLevelEmphasis = 0;
Radiomics.GLRLM_ShortRunHighGrayLevelEmphasis = 0;
Radiomics.GLRLM_LongRunLowGrayLevelEmphasis = 0;
Radiomics.GLRLM_LongRunHighGrayLevelEmphasis = 0;
j = (1:nLength)'.^2;
i = (1:nLevels)'.^2;
for k = 1:nMatrices
    p = glrlm(:,:,k);
    Radiomics.GLRLM_ShortRunEmphasis = sum(p*(1./j))/nMatrices+Radiomics.GLRLM_ShortRunEmphasis;
    Radiomics.GLRLM_LongRunEmphasis = sum(p*(j))/nMatrices+Radiomics.GLRLM_LongRunEmphasis;
    Radiomics.GLRLM_GrayLevelNonUniformity = sum(sum(p,2).^2)/nMatrices+Radiomics.GLRLM_GrayLevelNonUniformity;
    Radiomics.GLRLM_RunLengthNonUniformity = sum(sum(p,1).^2)/nMatrices+Radiomics.GLRLM_RunLengthNonUniformity;
    Radiomics.GLRLM_RunPercentage = sum(sum(p))/numel(p)/nMatrices+Radiomics.GLRLM_RunPercentage;
    Radiomics.GLRLM_LowGrayLevelRunEmphasis = sum((1./i)'*p)/nMatrices+Radiomics.GLRLM_LowGrayLevelRunEmphasis;
    Radiomics.GLRLM_HighGrayLevelRunEmphasis = sum(i'*p)/nMatrices+Radiomics.GLRLM_HighGrayLevelRunEmphasis;
    Radiomics.GLRLM_ShortRunLowGrayLevelEmphasis = (1./i)'*(p*(1./j))/nMatrices+Radiomics.GLRLM_ShortRunLowGrayLevelEmphasis;
    Radiomics.GLRLM_ShortRunHighGrayLevelEmphasis = (i)'*(p*(1./j))/nMatrices+Radiomics.GLRLM_ShortRunHighGrayLevelEmphasis;
    Radiomics.GLRLM_LongRunLowGrayLevelEmphasis = (1./i)'*(p*j)/nMatrices+Radiomics.GLRLM_LongRunLowGrayLevelEmphasis;
    Radiomics.GLRLM_LongRunHighGrayLevelEmphasis = i'*(p*(j))/nMatrices+Radiomics.GLRLM_LongRunHighGrayLevelEmphasis;
end